services:
  db:
    image: postgres:16-alpine
    container_name: mini-crm-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_crm
    ports:
      - "5432:5432"
    volumes:
      - mini_crm_pgdata:/var/lib/postgresql/data

volumes:
  mini_crm_pgdata:
